[project]
name = "trabalho"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=46.0.1",
    "fastapi[all]>=0.117.1",
    "pillow>=11.3.0",
    "pyotp>=2.9.0",
    "qrcode>=8.2",
    "requests>=2.32.5",
]
